import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";

const helvetica = localFont({
   src: "./fonts/HelveticaNowVar.ttf",
   variable: "--helvetica",
   weight: "100 900",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en'>
         <body className={`${helvetica.variable} arial sans-serif antialiased `}>
            <Header></Header>
            <main className='container'>{children}</main>
         </body>
      </html>
   );
}
